//
// Created by jolau on 29.03.19.
//

#ifndef VARILEG_LOWLEVEL_CONTROLLER_MOTORCONTROLLERSTATE_HPP
#define VARILEG_LOWLEVEL_CONTROLLER_MOTORCONTROLLERSTATE_HPP

enum class MotorControllerState {
  STATE_UNKNOWN = 0u,
  STATE_NOT_READY_TO_SWITCH_ON = 1u,
  STATE_SWITCH_ON_DISABLED = 2u,
  STATE_READY_TO_SWITCH_ON = 3u,
  STATE_SWITCHED_ON = 4u,
  STATE_OP_ENABLED = 5u,
  STATE_QUICK_STOP_ACTIVE = 6u,
  STATE_FAULT_REACTION_ACTIVE = 7u,
  STATE_FAULT = 8u,
};

#endif //VARILEG_LOWLEVEL_CONTROLLER_MOTORCONTROLLERSTATE_HPP
