//
// Created by jolau on 03.04.19.
//

#ifndef VARILEG_LOWLEVEL_CONTROLLER_OPERATINGMODE_HPP
#define VARILEG_LOWLEVEL_CONTROLLER_OPERATINGMODE_HPP

enum class OperatingMode {
  UNKNOWN,
  HOMING,
  CSP
};

#endif //VARILEG_LOWLEVEL_CONTROLLER_OPERATINGMODE_HPP
