left_bus_name: ens9
right_bus_name: enp4s0

publishers:
  joint_states:
    topic: joint_states
    queue_size: 1
    latch: false

  device_states:
    topic: device_states
    queue_size: 1
    latch: false

  joint_trajectories:
    topic: joint_trajectories
    queue_size: 1
    latch: false

subscribers:
  joint_trajectories:
    topic: joint_trajectories
    queue_size: 1
    latch: false

servers:
  set_device_state:
    service: set_device_state
  set_operating_mode:
    set_operating_mode: set_device_state