epos_mapping:
  hip_left: 1
  hip_right: 2
  knee_left: 5
  knee_right: 3

hip_left:
  primary_conversion_factor: 4611.04
  secondary_conversion_factor: -346321.156
  home_offset: 1.652
  crosscheck_margin_positive: 0.1
  crosscheck_margin_negative: 0.1
  min_position_limit: -0.262486554
  max_position_limit: 2.102923419

knee_left:
  primary_conversion_factor: 6413.94
  secondary_conversion_factor: -346321.156
  home_offset: -1.564
  crosscheck_margin_positive: 0.2
  crosscheck_margin_negative: 0.15
  min_position_limit: -2.109686427
  max_position_limit: -0.086748888

hip_right:
  primary_conversion_factor: -4611.67
  secondary_conversion_factor: 346321.156
  home_offset: 1.545
  crosscheck_margin_positive: 0.1
  crosscheck_margin_negative: 0.1
  min_position_limit: -0.262371299
  max_position_limit: 2.101197646

knee_right:
  primary_conversion_factor: -6418.40
  secondary_conversion_factor: 346321.156
  home_offset: -1.514
  crosscheck_margin_positive: 0.2
  crosscheck_margin_negative: 0.15
  min_position_limit: -2.093583697
  max_position_limit: -0.08700885

